# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - fix
    - title: Exciting New Features 🎉
      labels:
        - feat
        - update
    - title: Other Changes
      labels:
        - "*"
