# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-changes
        - major-updates
    - title: Exciting New Features 🎉
      labels:
        - feature
    - title: Patch updates
      labels:
        - bug
        - fix
    - title: Other Changes
      labels:
        - "*"
