# name: Publish package to Github
# on:
#   push:
#     branches: 
#       - main
# jobs:
#   npm-publish:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       # Setup .npmrc file to publish to npm
#       - name: Setup Node.js 16
#         uses: actions/setup-node@v2
        
#         with:
#           node-version: '16'
#           registry-url: 'https://registry.npmjs.org'
#       - name: Install npm
#         run: npm install

#       - name: Publish to Github
#         run:
#           npm config set registry https://npm.pkg.github.com &&
#           npm set //npm.pkg.github.com/:_authToken=${{env.NODE_AUTH_TOKEN}} &&
#           npm publish --registry https://npm.pkg.github.com
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.GIT_TOKEN}}

# pyruohbynuogugmt htyui67njr8gh56 ytubrtyubtyru
# tbyui tuitr yhuui irt uiygt